export enum ConfirmationType {
  RESERVATION_ACCEPT = 'RESERVATION_ACCEPT',
  RESERVATION_CANCEL = 'RESERVATION_CANCEL',
  RESERVATION_REJECT = 'RESERVATION_REJECT',
  RESERVATION_REQUEST_CANCEL = 'RESERVATION_REQUEST_CANCEL',
}
