export enum ReservationStatus {
  CREATED = 'CREATED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REQUESTED_CANCELLATION = 'REQUESTED_CANCELLATION',
  REJECTED_CANCELLATION = 'REJECTED_CANCELLATION',
}
