export enum SuccessType {
  ORGANIZATION_ADDED_TITLE = 'ORGANIZATION_ADDED_TITLE',
  ORGANIZATION_ADDED_DESC = 'ORGANIZATION_ADDED_DESC',
  RESERVATION_CREATED_TITLE = 'RESERVATION_CREATED_TITLE',
  RESERVATION_CREATED_DESC = 'RESERVATION_CREATED_DESC',
  RESERVATION_CANCELLED_TITLE = 'RESERVATION_CANCELLED_TITLE',
  RESERVATION_CANCELLED_DESC = 'RESERVATION_CANCELLED_DESC',
  PASSWORD_UPDATED_TITLE = 'PASSWORD_UPDATED_TITLE',
  PASSWORD_UPDATED_DESC = 'PASSWORD_UPDATED_DESC',
}
