export enum SettingKey {
  CONTACT_PHONE = 'CONTACT_PHONE',
  CONTACT_EMAIL = 'CONTACT_EMAIL',
  RESERVATION_CANCELLATION_WITHOUT_APPROVAL_HOURS = 'RESERVATION_CANCELLATION_WITHOUT_APPROVAL_HOURS',
  RESERVATION_OPENING_HOUR = 'RESERVATION_OPENING_HOUR',
  RESERVATION_CLOSING_HOUR = 'RESERVATION_CLOSING_HOUR',
  RESERVATION_REMINDER_HOUR = 'RESERVATION_REMINDER_HOUR',
}

export interface SettingMetadata {
  title: string;
  description?: string;
}
